#inherit_from: https://relaxed.ruby.style/rubocop.yml

Layout/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true