language: ruby
rvm:
  - 2.7.0
install:
  - bundle config set deployment 'true'
  - bundle config set without 'development'
  - bundle install
  - npm install
script:
  - bundle exec rspec
  - npm run test
